<option value="" {{ empty($selected) ? 'selected' : '' }}>選択してください</option>
<option value="1" {{ (isset($selected) && $selected === '1') ? 'selected' : '' }}>1</option>
<option value="2" {{ (isset($selected) && $selected === '2') ? 'selected' : '' }}>2</option>
<option value="3-1" {{ (isset($selected) && $selected === '3-1') ? 'selected' : '' }}>3-1</option>
<option value="3-2" {{ (isset($selected) && $selected === '3-2') ? 'selected' : '' }}>3-2</option>
<option value="3-3" {{ (isset($selected) && $selected === '3-3') ? 'selected' : '' }}>3-3</option>
<option value="4-A" {{ (isset($selected) && $selected === '4-A') ? 'selected' : '' }}>4-A</option>
<option value="4-1" {{ (isset($selected) && $selected === '4-1') ? 'selected' : '' }}>4-1</option>
<option value="4-2" {{ (isset($selected) && $selected === '4-2') ? 'selected' : '' }}>4-2</option>
<option value="4-3" {{ (isset($selected) && $selected === '4-3') ? 'selected' : '' }}>4-3</option>
<option value="4-4" {{ (isset($selected) && $selected === '4-4') ? 'selected' : '' }}>4-4</option>
<option value="5-1" {{ (isset($selected) && $selected === '5-1') ? 'selected' : '' }}>5-1</option>
<option value="5-2" {{ (isset($selected) && $selected === '5-2') ? 'selected' : '' }}>5-2</option>
<option value="6-A" {{ (isset($selected) && $selected === '6-A') ? 'selected' : '' }}>6-A</option>
<option value="6-1" {{ (isset($selected) && $selected === '6-1') ? 'selected' : '' }}>6-1</option>
<option value="6-2" {{ (isset($selected) && $selected === '6-2') ? 'selected' : '' }}>6-2</option>
<option value="6-3" {{ (isset($selected) && $selected === '6-3') ? 'selected' : '' }}>6-3</option>
<option value="6-4" {{ (isset($selected) && $selected === '6-4') ? 'selected' : '' }}>6-4</option>
<option value="6-5" {{ (isset($selected) && $selected === '6-5') ? 'selected' : '' }}>6-5</option>
<option value="設計" {{ (isset($selected) && $selected === '設計') ? 'selected' : '' }}>設計</option>
<option value="製造" {{ (isset($selected) && $selected === '製造') ? 'selected' : '' }}>製造</option>